version: '3.2'

services:

  stt-worker:
    container_name: stt-standalone-worker
    build: .
    image: lintoai/linto-platform-stt-standalone-worker
    volumes:
      - ${AM_PATH}:/opt/models/AM
      - ${LM_PATH}:/opt/models/LM
    ports:
      - ${WORKER_PORT}:${SERVICE_PORT}
    env_file: .env
    environment:
      - ${SERVICE_PORT}

  swaggerui:
    image: swaggerapi/swagger-ui
    ports:
      - 80:8080
    hostname: swaggerui
    volumes:
      - ${SWAGGER_PATH}:/app/swagger/
    env_file: .env
    environment:
      - SWAGGER_JSON
